### ISSUE TITLE
StatusRuntimeException: UNIMPLEMENTED: unknown service opentelemetry.proto.collector.metrics.v1.MetricsService

### ISSUE THREAD

**Issue by marcellodesales** [joe-elliott/tempo-springboot-example#10]
```
tomcat_service | [opentelemetry.auto.trace 2021-08-24 04:10:51:215 +0000] [grpc-default-executor-0] WARN io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter - Failed to export metrics
tomcat_service | io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service opentelemetry.proto.collector.metrics.v1.MetricsService
tomcat_service | 	at io.grpc.Status.asRuntimeException(Status.java:534)
tomcat_service | 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
tomcat_service | 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
tomcat_service | 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
tomcat_service | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
tomcat_service | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
tomcat_service | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
tomcat_service | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
tomcat_service | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
tomcat_service | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
tomcat_service | 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by joe-elliott** [comment]
This occurs when you point the otel client at a backend that does not support metrics. I believe setting the env var:

```OTEL_EXPORTER=otlp_span```

should tell it to only export trace data.
